### PR TITLE
Parse mesh info

### PR DESCRIPTION
**Pull request by raypereda-gr**

### CODE REVIEW

**Comment by raypereda-gr** [comment]
This PR adds three new dictionary keys with string values.

"**mesh_subheadings**" - example: "Q000032:analysis; Q000276:immunology"
"**mesh_major_topics**" - example: "Q000032:analysis; Q000276:immunology; D005455:Fluorescent " \
                                                     "Antibody Technique; D011529:Protozoan Infections, Animal"
"**mesh_full_terms**" - example "D000818:Animals; D000906/Q000032:Antibodies/analysis*; " \
                                                   "D004283/Q000276:Dog Diseases/immunology*; D004285:Dogs; " \
                                                   "D056890/Q000276:Eukaryota/immunology*; D005455:Fluorescent " \
                                                   "Antibody Technique*; D011528/Q000276:Protozoan " \
                                                   "Infections/immunology; D011529:Protozoan Infections, Animal*"
"**mesh_terms**" - example "D000293:Adolescent; D000328:Adult; D000368:Aged; D001249:Asthma;
D001993:Bronchodilator Agents; D019819:Budesonide; D002648:Child; D004311:Double-Blind Method;
D004334:Drug Administration Schedule; D004338:Drug Combinations; D005260:Female; 
D005541:Forced Expiratory Volume; D000068759:Formoterol Fumarate; D005938:Glucocorticoids;
D006801:Humans; D060046:Maintenance Chemotherapy; D008297:Male;
D055118:Medication Adherence; D008875:Middle Aged; D011795:Surveys and Questionnaires; D013726:Terbutaline
D055815:Young Adult"

@nicholasjuncos will all three of new lists be used during Solr indexing?
image
Is possible to map the lists into each of the 4 terms lists into one of the PubMed website field indexing?
MeSH Major Topic
MeSH subheading (are these the opposite of Major topic?
MeSH terms
Other terms (??)

We have a Major topic but I don't see Minor Topic. For the purposes of the code, can we use more tidy names of the list and clear show how they are related to each other?

I don't see PubMed website allowing searching based on whether the term is major or minor term.

**Comment by nicholasjuncos** [comment]
@raypereda-gr 
1. **_Will all three of new lists be used during Solr indexing?_**: Yes, all three will be added to solr indexing in 3 different fields.
2. **_Is possible to map the lists into each of the 4 terms lists into one of the PubMed website field indexing?_**: The 3 new lists (mesh_subheadings_list, mesh_major_topics_list, and mesh_full_terms_list) match to PubMed index fields. mesh_subheading_list -> MeSH Subheading, mesh_major_topics_list -> MeSH Major Topics, and mesh_full_terms_list -> MeSH Terms. The only list that does NOT link to an index field is "mesh_terms_list". This was due to improper naming on the library owner. That list should technically be named "mesh_headings_list", but at this point, there are too many users utilizing this library to change their naming convention, which is why I had to go with "mesh_full_terms".
3. **_Other Term Field_**: Do not worry about this field for this PR, it does not relate to MeSH terms at all. We will get this info in the future.
4. **_What is a MeSH Subheading?_**: MeSh Subheadings are the part of the MeSH term that is AFTER a "/". So when you see a MeSH Term of "Budesonide/therapeutic use", then "therapeutic use" is a subheading. Subheadings can be Major Topics as well, so they are not the opposite of Major Topics.
5. **_Major Topics_**: A major topic is designated by the "\*" in a MeSH Term. Example1: "Budesonide*", budesonide is a Major Topic. Example 2: "Budesonide/therapeutic use*", therapeutic use is a Major Topic. PubMed does not have a "MeSH Minor Topics" field, although it would be possible to search for "minor topics" by simply adding NOT before the query part of "MeSH Major Topics". Example: `"budesonide"[MeSH Terms] NOT "budesonide"[MeSH Major Topic]` . PubMed allows you to search in Advanced Search on if a term is a major topic, as seen in previous example.

**Comment by raypereda-gr** [comment]
The scope of the pubmed_parser scope should not include functions that are specific to indexing Solr. Subheadings are a good example of that. Indexing subheading without the context of the description loses information. Even thought PubMed website is indexing on subheading, we should consider more sensible indexing.

For speed, each XML node should be scanned only once. Making 4 passes with 4 functions is not efficient. The code come becomes more complex with functions that are not clearly named for historical reasons. To understand the functions, you need to read the internal code, and see examples input and output. 

I don't recommending the parsing mesh terms with four passing. Why? Performance and not concise.

The code to process subheading should go in the `pubmed-import` repo, a client of pubmed-parser.
```python
import pprint
pp = pprint.PrettyPrinter(indent=4)

mesh_terms = """D000280:Administration, Inhalation
D000293:Adolescent
D000328:Adult
D000368:Aged
D001249:Asthma / Q000188:drug therapy*
D001993:Bronchodilator Agents / Q000008:administration & dosage* / Q000009:adverse effects
D019819:Budesonide / Q000008:administration & dosage* / Q000009:adverse effects
D002648:Child
D004311:Double-Blind Method
D004334:Drug Administration Schedule
D004338:Drug Combinations
D005260:Female
D005541:Forced Expiratory Volume
D000068759:Formoterol Fumarate / Q000008:administration & dosage* / Q000009:adverse effects
D005938:Glucocorticoids / Q000008:administration & dosage
D006801:Humans
D060046:Maintenance Chemotherapy
D008297:Male
D055118:Medication Adherence
D008875:Middle Aged
D011795:Surveys and Questionnaires
D013726:Terbutaline / Q000008:administration & dosage* / Q000009:adverse effects
D055815:Young Adult""".replace("\n", "; ")

# a convenience function defined in the pubmed-parser update.
def split_mesh(mesh_terms):
    mesh_list = []
    for term in mesh_terms.split("; "):
        subs = []
        for subterm in term.split(" / "):
            ui, descriptor = subterm.split(":")
            subs.append((ui, descriptor))
        mesh_list.append(subs)
    return mesh_list

terms = split_mesh(mesh_terms)
# pp.pprint(terms)
# Output:
# [   [('D000280', 'Administration, Inhalation')],
#     [('D000293', 'Adolescent')],
#     [('D000328', 'Adult')],
#     [('D000368', 'Aged')],
#     [('D001249', 'Asthma'), ('Q000188', 'drug therapy*')],
#     [   ('D001993', 'Bronchodilator Agents'),
#         ('Q000008', 'administration & dosage*'),
#         ('Q000009', 'adverse effects')],
#     [   ('D019819', 'Budesonide'),
#         ('Q000008', 'administration & dosage*'),
#         ('Q000009', 'adverse effects')],
#     [('D002648', 'Child')],
#     [('D004311', 'Double-Blind Method')],
#     [('D004334', 'Drug Administration Schedule')],
#     [('D004338', 'Drug Combinations')],
#     [('D005260', 'Female')],
#     [('D005541', 'Forced Expiratory Volume')],
#     [   ('D000068759', 'Formoterol Fumarate'),
#         ('Q000008', 'administration & dosage*'),
#         ('Q000009', 'adverse effects')],
#     [('D005938', 'Glucocorticoids'), ('Q000008', 'administration & dosage')],
#     [('D006801', 'Humans')],
#     [('D060046', 'Maintenance Chemotherapy')],
#     [('D008297', 'Male')],
#     [('D055118', 'Medication Adherence')],
#     [('D008875', 'Middle Aged')],
#     [('D011795', 'Surveys and Questionnaires')],
#     [   ('D013726', 'Terbutaline'),
#         ('Q000008', 'administration & dosage*'),
#         ('Q000009', 'adverse effects')],
#     [('D055815', 'Young Adult')]]

# qualifier is aka subheading
qualifier_set = set()
for term in terms:
    for qualifier in term[1:]:
        qualifier_set.add(qualifier[1])

pp.pprint(qualifier_set)
# Output:
# {   'administration & dosage',
#     'administration & dosage*',
#     'adverse effects',
#     'drug therapy*'}


```

**Comment by nicholasjuncos** [comment]
I understand your outlook with pubmed parser’s scope. My thought is that this is actually parsing information that can be used by others from a pubmed article. After all, there are many reasons to utilize these other fields outside of SOLR. In terms of PubMed's indexing, I think it is best that we duplicate what PubMed is doing as we are currently trying to duplicate their exact search results.

I fully agree with not parsing the terms with four passings of four functions, which is why I developed the current singular function that pulls all of the information in one passing, without the need of adding any extra function to pull the subheadings, and other mesh info. As mentioned in the meeting, I found some really great results with this function. The timing was nearly exact with the current version of pubmed parser, sometimes the new version would be faster, sometimes slower. I left the old functions in the code in case someone wanted to import them individually for their own needs, but perhaps it is best that we remove them to reduce confusion.

**Comment by DustinHolden** [comment]
> The scope of the pubmed_parser scope should not include functions that are specific to indexing Solr. Subheadings are a good example of that. Indexing subheading without the context of the description loses information. Even thought PubMed website is indexing on subheading, we should consider more sensible indexing.

We are needing to replicate PubMed search due to the expectations and requirements of clients. Whether PubMed is making a bad or good decision with the indexes on subheadings is irrelevant. If we want to make an "improved" search or better indexing strategies, we can, but that isn't part of the current task.

> For speed, each XML node should be scanned only once. Making 4 passes with 4 functions is not efficient. The code come becomes more complex with functions that are not clearly named for historical reasons. To understand the functions, you need to read the internal code, and see examples input and output.

I think there may be some confusion here, I don't see the 4 passes and 4 functions being used. I think `parse_mesh_info` is the only function still in use on this PR. `parse_mesh_full_terms`, `parse_mesh_major_topics`, and `parse_mesh_subheadings` are not used and could be removed. Which, I notice that Nico has removed in a recent commit.

---

When comparing the two PRs (#1 and [public](https://github.com/titipata/pubmed_parser/pull/117)) I'm seeing two different approaches. Nico's approach is to break the new subheadings into their own dictionary values, whereas Ray is creating them as a text list that can be split apart later.

I'm not sure which approach fits best with the current communities use of `pubmed_parser`, but I know my preferences is interacting with dictionaries.

**Pull request merged**
